import jwt from 'jsonwebtoken'; import User from '../models/User.js'; import Project from '../models/Project.js'; import Enquiry from '../models/Enquiry.js'
const sign=id=>jwt.sign({id},process.env.JWT_SECRET,{expiresIn:process.env.JWT_EXPIRES_IN||'1d'})
export async function login(req,res,next){try{const {email,password}=req.body;const user=await User.findOne({email:email?.toLowerCase()}).select('+password');if(!user||!(await user.comparePassword(password||'')))return res.status(401).json({message:'Incorrect email or password'});res.json({token:sign(user._id),user:{name:user.name,email:user.email}})}catch(e){next(e)}}
export async function stats(req,res,next){try{const [totalProjects,featuredProjects,newEnquiries,totalEnquiries]=await Promise.all([Project.countDocuments(),Project.countDocuments({featured:true}),Enquiry.countDocuments({status:'new'}),Enquiry.countDocuments()]);res.json({totalProjects,featuredProjects,newEnquiries,totalEnquiries})}catch(e){next(e)}}
export async function projects(req,res,next){try{res.json(await Project.find().sort({createdAt:-1}))}catch(e){next(e)}}
export async function createProject(req,res,next){try{res.status(201).json(await Project.create(req.body))}catch(e){next(e)}}
export async function updateProject(req,res,next){try{const item=await Project.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(!item)return res.status(404).json({message:'Project not found'});res.json(item)}catch(e){next(e)}}
export async function deleteProject(req,res,next){try{const item=await Project.findByIdAndDelete(req.params.id);if(!item)return res.status(404).json({message:'Project not found'});res.json({message:'Project deleted'})}catch(e){next(e)}}
export async function enquiries(req,res,next){try{const query=req.query.status?{status:req.query.status}:{};res.json(await Enquiry.find(query).sort({createdAt:-1}))}catch(e){next(e)}}
export async function enquiry(req,res,next){try{const item=await Enquiry.findById(req.params.id);if(!item)return res.status(404).json({message:'Enquiry not found'});res.json(item)}catch(e){next(e)}}
export async function updateStatus(req,res,next){try{const allowed=['new','contacted','qualified','converted','closed'];if(!allowed.includes(req.body.status))return res.status(400).json({message:'Invalid status'});const item=await Enquiry.findByIdAndUpdate(req.params.id,{status:req.body.status},{new:true});if(!item)return res.status(404).json({message:'Enquiry not found'});res.json(item)}catch(e){next(e)}}
